# Lewis Hamilton v. Top Drivers

Lewis Hamilton is a six-time Forumla One World Champion and lightly regarded as the greatest Formula One Driver of all time. He won his first World Driver's Championship with McLaren in 2008 and then moved to Mercedes, where he proceeded to win his 5 remaining titles. The notebook will observe Hamilton in comparison to his competitors. What records and how many does he hold? How did he fare in races compared to other legends? Finally, is the driver or their car that decides success?

In [2]:
# import dependencies

import numpy as np
import pandas as pd
import datetime as datetime
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
from datetime import date
warnings.filterwarnings("ignore")

In [3]:
#read in csv's and create needed data frames

def getMiliSeconds(time):
    try:
        if '.' in time:
            x = datetime.datetime.strptime(time,'%M:%S.%f')
        elif ',' in time:
            x = datetime.datetime.strptime(time,'%M:%S,%f')
        else:
            x = datetime.datetime.strptime(time,'%M:%S:%f')
        return datetime.timedelta(minutes=x.minute,seconds=x.second, microseconds = x.microsecond).total_seconds()
    except:
        x = datetime.datetime.strptime(str(time).split('.')[0],'%M:%S:%f')
        return datetime.timedelta(minutes=x.minute,seconds=x.second, microseconds = x.microsecond).total_seconds()

def wins_per_year(driverRef, year):
    try:
        return topTenYears.loc[(topTenYears['driverRef'] == driverRef) & (topTenYears['positionOrder'] == 1) & (topTenYears['year'] == year)].groupby('driverId')['raceId'].count().values[0]
    except:
        return 0

def championsInYears(years, driverRef):
    total = []
    t = 0
    for year in years:
        winner = r.loc[r['year']== year].groupby('driverRef')['points'].sum().sort_values(ascending = False).index[0]
        if winner == driverRef:
            t = t + 1
        total.append(t)
    return total

df_races  = pd.read_csv('Resources/races.csv')
df_drivers = pd.read_csv('Resources/drivers.csv',encoding='latin1')
df_circuit = pd.read_csv('Resources/circuits.csv',encoding='latin-1')
df_constructors = pd.read_csv('Resources/constructors.csv',encoding='latin-1')
df_qualy = pd.read_csv('Resources/qualifying.csv',encoding='latin-1')
df_results = pd.read_csv('Resources/results.csv',encoding='latin-1')
df_status = pd.read_csv('Resources/status.csv')
df_timeLaps = pd.read_csv('Resources/lap_times.csv')

df_races = df_races.drop(['time','url','round','circuitId'],axis=1)
df_drivers = df_drivers.drop(['number','code','url'], axis=1)
df_constructors = df_constructors.drop(['nationality','constructorRef','url','name'], axis=1)
df_results = df_results.drop(['number','grid','positionText','position','laps','time','milliseconds','rank','fastestLap','fastestLapSpeed','resultId'], axis=1)
df_timeLaps = df_timeLaps.drop(['milliseconds'],axis = 1)

df_results['fastestLapTime'] = df_results['fastestLapTime'].fillna('00:00.0')
df_qualy['q1'] = df_qualy['q1'].fillna('00:00.0')
df_qualy['q2'] = df_qualy['q2'].fillna('00:00.0')
df_qualy['q3'] = df_qualy['q3'].fillna('00:00.0')
df_timeLaps['time'] = df_timeLaps['time'].fillna('00:00.0')

df_qualy['q1'] = df_qualy['q1'].apply(lambda x: getMiliSeconds(x))
df_qualy['q2'] = df_qualy['q2'].apply(lambda x: getMiliSeconds(x))
df_qualy['q3'] = df_qualy['q3'].apply(lambda x: getMiliSeconds(x))
df_timeLaps['time'] = df_timeLaps['time'].apply(lambda x: getMiliSeconds(x))
df_results['fastestLapTime'] = df_results['fastestLapTime'].apply(lambda x: getMiliSeconds(x))

df_drivers['fullName'] = df_drivers['forename'] +" "+ df_drivers['surname']

In [7]:
#Build Dataframes by Nationality

nationality_data=[]

nationality = pd.merge(df_drivers,df_results, on='driverId',how='inner')
nationality1 = nationality.loc[nationality['positionOrder']==1]
#nationality1['freq']=
nationality1.groupby(by='nationality')['positionOrder'].transform('count').sort_values()
#nationality1 = nationality1[nationality1["freq"] >20 ]
nationality2 = nationality1.drop_duplicates(subset=['nationality'])

nationality2

,driverId,driverRef,forename,surname,dob,nationality,fullName,raceId,constructorId,positionOrder,points,fastestLapTime,statusId
0,1,hamilton,Lewis,Hamilton,1/7/1985,British,Lewis Hamilton,18,1,1,10.0,87.5,1
556,3,rosberg,Nico,Rosberg,6/27/1985,German,Nico Rosberg,862,131,1,25.0,101.0,1
666,4,alonso,Fernando,Alonso,7/29/1981,Spanish,Fernando Alonso,32,4,1,10.0,105.8,1
976,5,kovalainen,Heikki,Kovalainen,10/19/1981,Finnish,Heikki Kovalainen,28,1,1,10.0,81.8,1
1474,9,kubica,Robert,Kubica,12/7/1984,Polish,Robert Kubica,24,2,1,10.0,77.5,1
1781,13,massa,Felipe,Massa,4/25/1981,Brazilian,Felipe Massa,20,6,1,10.0,93.6,1
2374,15,trulli,Jarno,Trulli,7/13/1974,Italian,Jarno Trulli,95,4,1,10.0,74.9,1
2812,17,webber,Mark,Webber,8/27/1976,Australian,Mark Webber,9,9,1,10.0,94.0,1
4793,31,montoya,Juan,Pablo Montoya,9/20/1975,Colombian,Juan Pablo Montoya,81,1,1,10.0,80.7,1
5095,35,villeneuve,Jacques,Villeneuve,4/9/1971,Canadian,Jacques Villeneuve,208,3,1,10.0,0.0,1
5511,44,panis,Olivier,Panis,9/2/1966,French,Olivier Panis,229,27,1,10.0,0.0,1
7382,77,berger,Gerhard,Berger,8/27/1959,Austrian,Gerhard Berger,216,22,1,10.0,0.0,1
10726,123,boutsen,Thierry,Boutsen,7/13/1957,Belgian,Thierry Boutsen,330,3,1,9.0,0.0,1
14691,199,reutemann,Carlos,Reutemann,4/12/1942,Argentine,Carlos Reutemann,484,3,1,9.0,0.0,1
15259,207,mario_andretti,Mario,Andretti,2/28/1940,American,Mario Andretti,527,32,1,9.0,0.0,1
15686,222,scheckter,Jody,Scheckter,1/29/1950,South African,Jody Scheckter,517,6,1,9.0,0.0,1
15792,223,regazzoni,Clay,Regazzoni,9/5/1939,Swiss,Clay Regazzoni,520,3,1,9.0,0.0,1
16594,238,peterson,Ronnie,Peterson,2/14/1944,Swedish,Ronnie Peterson,529,32,1,9.0,0.0,1
17728,304,hulme,Denny,Hulme,6/18/1936,New Zealander,Denny Hulme,590,1,1,9.0,0.0,1
18632,345,rodriguez,Pedro,RodrÃ­guez,1/18/1940,Mexican,Pedro RodrÃ­guez,646,66,1,9.0,0.0,1
22805,813,maldonado,Pastor,Maldonado,3/9/1985,Venezuelan,Pastor Maldonado,864,3,1,25.0,87.9,1
24086,830,max_verstappen,Max,Verstappen,9/30/1997,Dutch,Max Verstappen,952,9,1,25.0,88.8,1
24707,844,leclerc,Charles,Leclerc,10/16/1997,Monegasque,Charles Leclerc,1022,6,1,25.0,106.7,1